// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrV8E7-8zKkkoLtpyXEZOItZtm2fU5TE',
    appId: '1:1001969369914:web:39799ca218228f711a4603',
    messagingSenderId: '1001969369914',
    projectId: 'agromind-b2196',
    authDomain: 'agromind-b2196.firebaseapp.com',
    storageBucket: 'agromind-b2196.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwe2OSvERpwIPslcoXWE5BqbTaW8VCKPs',
    appId: '1:1001969369914:android:6c3abb0e13caad511a4603',
    messagingSenderId: '1001969369914',
    projectId: 'agromind-b2196',
    storageBucket: 'agromind-b2196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8pNYwnk4iYS2LCSoVkqd2bbcTgnLxFE',
    appId: '1:1001969369914:ios:28e3785757563d701a4603',
    messagingSenderId: '1001969369914',
    projectId: 'agromind-b2196',
    storageBucket: 'agromind-b2196.firebasestorage.app',
    iosBundleId: 'com.nursematurhan.agromind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8pNYwnk4iYS2LCSoVkqd2bbcTgnLxFE',
    appId: '1:1001969369914:ios:28e3785757563d701a4603',
    messagingSenderId: '1001969369914',
    projectId: 'agromind-b2196',
    storageBucket: 'agromind-b2196.firebasestorage.app',
    iosBundleId: 'com.nursematurhan.agromind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJrV8E7-8zKkkoLtpyXEZOItZtm2fU5TE',
    appId: '1:1001969369914:web:4619dc8f056fe6071a4603',
    messagingSenderId: '1001969369914',
    projectId: 'agromind-b2196',
    authDomain: 'agromind-b2196.firebaseapp.com',
    storageBucket: 'agromind-b2196.firebasestorage.app',
  );

}